---
- name: Get File from Server
  hosts: windows-stigtest
  tasks:
    - name: Fetch file 
      ansible.builtin.fetch:
        src: C:\Users\ec2-user\SCC\Config\5.5_options.xml
        dest: /files/scc_config/
