---
- name: Get File from Server
  hosts: {{ HOSTS | default('windows') }}
  tasks:
    - name: 
      ansible.builtin.fetch:
        src: C:\SSC\CONFIG\5.5_options.yml
        dest: /tmp/
        flat: yes
