---
- name: Get File from Server
  hosts: os_windows
  vars:
    
  tasks:
    - name: find checklists
      ansible.windows.win_find:
        paths: C:\checklists\
        file_type: file
      register: files
    
    - name: check the content and structure of the variable
      debug: 
        var: files
   
    #- name: Fetch files 
    #  ansible.builtin.fetch:
    #    src: "{{ item.path }}"
    #    dest: /tmp/
    #  with_items: "{{files.files}}"
      
    - name: copy files to tmp
      ansible.builtin.copy:
        remote_src: "{{ item.path }}"
        dest: /checklists
      with_items: "{{files.files}}"
      delegate_to: linux1
      
  
