---
- name: Get File from Server
  hosts: os_windows
  vars:
    
  tasks:
    - name: find checklists
      ansible.windows.win_find:
        paths: C:\checklists\
        file_type: file
      register: files
    
    - name: check the content and structure of the variable
      debug: 
        var: files
   
    - name: Fetch files 
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{files.files}}"
      
    - name: copy ckls to ansible server
      ansible.builtin.copy:
        src: "/tmp/{{ item.path | basename }}"
        dest: /checklists
      with_items: "{{files.files}}"
      delegate_to: backup-server
      
  
