---
- name: Get File from Server
  hosts: windows-stigtest
  tasks:
    - name: Fetch file 
      ansible.builtin.fetch:
        src: C:\SSC\CONFIG\5.5_options.yml
        dest: /tmp/
        flat: yes
