---
- name: Get File from Server
  hosts: os_windows
  vars:
    device_type: windows
    src_dir: C:\checklists\
    copy_dir: /home/ec2-user/checklists
    
  tasks:
    - name: find checklists
      ansible.windows.win_find:
        paths: "{{ src_dir }}"
        file_type: file
      register: files
    
    - name: check the content and structure of the variable
      debug: 
        var: files
   
    - name: Fetch files 
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /tmp/
        flat: yes
      with_items: "{{files.files}}"
      
    - name: copy ckls to {{ copy_dir }}
      ansible.builtin.copy:
        src: "/tmp/{{ item.filename }}"
        dest: "{{ copy_dir }}/{{ device_type }}"
      with_items: "{{files.files}}"
      delegate_to: backup-server
      
  
