---
- name: Modify CKL Files
  hosts: "{{ HOSTS | default('os_windows') }}"
  tasks:
    - name: Change Comment in CKL File
      community.windows.win_lineinfile:
        path: "{{ file_name }}"
        regex: '<COMMENTS></COMMENTS>'
        line: '<COMMENTS>"{{ comment }}"</COMMENTS>'
      with_sequence: start=1 end=205
