---
- name: SCAP Compliance Checker
  hosts: "{{ HOSTS | default('windows') }}"
  gather_facts: false
  tasks:
  - name: Create TEMP directory
    ansible.windows.win_file:
      path: C:\Temp\
      state: directory
      
  - name: Download SCC from DISA
    ansible.windows.win_get_url:
      url: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.5_Windows_bundle.zip
      dest: C:\Temp\scc-5.5_Windows_bundle.zip
      force: no
      validate_certs: no
   
  - name: Unzip SCC Windows Bundle
    community.windows.win_unzip:
      src: C:\Temp\scc-5.5_Windows_bundle.zip
      
  - name: Unzip exe to SCC dir
    community.windows.win_unzip:
      src: C:\Temp\scc-5.5_Windows_bundle\scc-5.5_Windows\scc-5.5_Windows.zip
      dest: C:\SCC
      creates: C:\SCC

  
  - name: Run SCAP Scan
    ansible.windows.win_command: cscc.exe --help config
    args:
      chdir: C:\SCC\scc_5.5

    register: scc_output

  - debug:
      var: scc_output
