---
- name: SCAP Compliance Checker
  hosts: "{{ HOSTS | default('linux') }}"
  gather_facts: false
  become: yes
  vars:
    scc_zipfile: scc-5.5_rhel8_oracle-linux8_x86_64_bundle.zip
    scc_version: scc-5.5_rhel8_x86_64
  tasks:
        
  - name: Download SCC from DISA
    ansible.builtin.get_url:
      url: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/{{ scc_zipfile }}
      dest: /tmp
      force: no
      validate_certs: no
   
  - name: Unzip SCC Linux Bundle
    ansible.builtin.unarchive:
      src: /tmp/{{ scc_zipfile }}
      dest: /tmp
      remote_src: yes
      
  - name: Install SCC local rpm file
    ansible.builtin.yum:
      name: /tmp/{{ scc_version }}/{{ scc_version }}.rpm
      state: present
  
  - name: Run SCAP Scan
    ansible.builtin.command: /opt/scc/cscc
    
    register: scc_output

  - debug:
      var: scc_output
