---
- name: SCAP Compliance Checker
  hosts: "{{ HOSTS | default('linux') }}"
  gather_facts: false
  tasks:
  - name: Create TEMP directory
    ansible.windows.win_file:
      path: C:\Temp\
      state: directory
      
  - name: Download SCC from DISA
    ansible.windows.win_get_url:
      url: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.5_rhel8_oracle-linux8_x86_64_bundle.zip
      dest: /tmp
      force: no
      validate_certs: no
   
  - name: Unzip SCC Linux Bundle
    community.windows.win_unzip:
      src: /tmp/scc-5.5_rhel8_oracle-linux8_x86_64_bundle.zip
      dest: /tmp
      
  - name: Unzip exe to SCC dir
    community.windows.win_unzip:
      src: C:\Temp\scc-5.5_Windows\scc-5.5_Windows.zip
      dest: /SCC
      creates: /SCC

  
  - name: Run SCAP Scan
    command: 
    args:
      chdir: C:\SCC\scc_5.5

    register: scc_output

  - debug:
      var: scc_output
